# Generated by Django 5.1.2 on 2024-10-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=800)),
                ('slug', models.SlugField(max_length=1000, unique=True)),
            ],
        ),
    ]
